### ISSUE TITLE
Crash when reading savegames created after GU7

### ISSUE THREAD

**Issue by Omally-aka-gargales** [Veraatversus/AnnoSavegameViewer#1]
Version 1.0 crashes when reading savegames created after Anno 1800 game update 7.

**Comment by Veraatversus** [comment]
the problem atm is that i dont have a update 7 savegame and i doesnt own the dlc. i have upgraded the savegameviewer on the first day of release but have had no chance to try my build. you can test the build at https://drive.google.com/open?id=1s1H8j4tL9HAJ-zW9SpF-jV1YL-krrbCm or send me an savegame^^. and i would be happy over an respone.

**Comment by Omally-aka-gargales** [comment]
Thanks for the quick answer. I have tested the new build and unfortunately the same problem occurs. I send you my savegame via DM using Zazunos discord. Hope you are okay with that.

**Comment by Veraatversus** [comment]
Hab nix bekommen bisher ;)

**Comment by Omally-aka-gargales** [comment]
Hmm. Ich habe an an beide Veras bei Zazuno geschrieben. Versuchen wir es doch mal andersherum. Meine Discord ID ist:
 Omally aka gargales #5272

**Comment by Veraatversus** [comment]
Ganz oben mit unter modders oder so bin ich

**Comment by Veraatversus** [comment]
Fixed with version 2.0
