### ISSUE TITLE
Editing Values in Savefiles

### ISSUE THREAD

**Issue by LePheel** [Veraatversus/AnnoSavegameViewer#5]
Apologies if this is not the right place to share, but I haven't seen anywhere else with a save parser.
In your experience, do you know if it is possible to edit the values in the save files? The reason I ask is because I have been tinkering with my mods to add new sessions, but after many hours of playing, I learned that these additional sessions cause graphical errors in Cape Trelawney (constant shadow flickering), and I would like to remove those sessions from the save so that I can load the save without them enabled.

**Comment by Veraatversus** [comment]
sry cant do this
